name: thuru_care_client
description: Thuru Care Client application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter:
  path_provider:
  flutter_image_compress: ^0.6.3
  fluttertoast:
  image_picker:
  photo_view: ^0.4.2
  zoomable_image:
  camera:
  google_maps_flutter:
  flutter_cache_manager:
  parallax_image:
  intl:
  geocoder:
  location: ^2.3.5
  shared_preferences:
  #simple_permissions:
  percent_indicator:
  rflutter_alert:
  rich_alert:
  liquid_pull_to_refresh: ^1.1.1
  json_annotation:
  mime:
  firebase_storage:
  firebase_database:
  firebase_core:
  scoped_model:
  provider: ^3.0.0+1
  firebase_auth: ^0.14.0
  cloud_firestore: ^0.12.9
  google_sign_in: ^3.2.4
  bubble_tab_indicator: ^0.1.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  json_serializable:

  flutter_cameraview:
    git:
      url: https://github.com/hramaroson/flutter_cameraview.git

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/title.png
    - assets/title_black.png
    - assets/logo.png
    - assets/title_green.png
    - assets/images/ic_flutter_devs_logo.png
    - assets/images/ic_powered_by.png
    - assets/images/ic_shutter_1.png
    - assets/images/ic_switch_camera_3.png
    - assets/images/ic_no_image.png
    - assets/images/ic_flash_camera.png
    - assets/images/ic_flash_camera_auto.png
    - assets/images/ic_flash_camera_off.png
    - assets/images/ic_flash_camera_tourch.png
    - assets/fruits_and_vegitables.png
    - assets/images/intro_page1.png
    - assets/images/intro_page2.png
    - assets/images/intro_page3.png
    - assets/images/community_tc.png
    - assets/images/login.png
    - assets/images/register.png
    - assets/images/profile.png
    - assets/icon/ic_my_garden.png
    - assets/map/
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Regular.ttf
    - family: ThuruCareIcons
      fonts:
        - asset: fonts/ThuruCareIcons.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
