/// Flutter icons ThuruCareIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ThuruCareIcons
///      fonts:
///       - asset: fonts/ThuruCareIcons.ttf
///
/// 
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Zocial, Copyright (C) 2012 by Sam Collins
///         Author:    Sam Collins
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  http://zocial.smcllns.com/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
/// * Web Symbols, Copyright (c) 2011 by Just Be Nice studio. All rights reserved.
///         Author:    Just Be Nice studio
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.justbenicestudio.com/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Brandico, (C) 2012 by Vitaly Puzrin
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  
///
import 'package:flutter/widgets.dart';

class ThuruCareIcons {
  ThuruCareIcons._();

  static const _kFontFam = 'ThuruCareIcons';

  static const IconData comment = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData location = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData picture = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData graduation_cap = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData key = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData cog = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData lightbulb = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData heart = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData mail = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData camera = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData beach_access = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData done = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData share = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData user_add = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData user_1 = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData user_add_outline = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData user_outline = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData users_outline = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData user_delete_outline = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData verified_user = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData diamond = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData youtube = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData shop = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData money = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData appstore = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData android = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData viadeo = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData truck = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData beaker = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData note = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData calendar = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData globe = const IconData(0xe821, fontFamily: _kFontFam);
  static const IconData paper_plane = const IconData(0xe822, fontFamily: _kFontFam);
  static const IconData fire = const IconData(0xe823, fontFamily: _kFontFam);
  static const IconData megaphone = const IconData(0xe824, fontFamily: _kFontFam);
  static const IconData thumbs_up_1 = const IconData(0xe825, fontFamily: _kFontFam);
  static const IconData tag = const IconData(0xe826, fontFamily: _kFontFam);
  static const IconData picture_1 = const IconData(0xe827, fontFamily: _kFontFam);
  static const IconData eye = const IconData(0xe828, fontFamily: _kFontFam);
  static const IconData lock = const IconData(0xe829, fontFamily: _kFontFam);
  static const IconData user_2 = const IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData users = const IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData attach = const IconData(0xe82c, fontFamily: _kFontFam);
  static const IconData star = const IconData(0xe82d, fontFamily: _kFontFam);
  static const IconData doc = const IconData(0xe82e, fontFamily: _kFontFam);
  static const IconData trash = const IconData(0xe82f, fontFamily: _kFontFam);
  static const IconData heart_1 = const IconData(0xe830, fontFamily: _kFontFam);
  static const IconData sort_alpha_asc = const IconData(0xe831, fontFamily: _kFontFam);
  static const IconData graduation_hat = const IconData(0xe832, fontFamily: _kFontFam);
  static const IconData map_marker = const IconData(0xe833, fontFamily: _kFontFam);
  static const IconData a2z = const IconData(0xe834, fontFamily: _kFontFam);
  static const IconData bacteria = const IconData(0xe835, fontFamily: _kFontFam);
  static const IconData deficiency = const IconData(0xe836, fontFamily: _kFontFam);
  static const IconData fungus = const IconData(0xe837, fontFamily: _kFontFam);
  static const IconData gallery = const IconData(0xe838, fontFamily: _kFontFam);
  static const IconData language = const IconData(0xe839, fontFamily: _kFontFam);
  static const IconData pencil = const IconData(0xe83a, fontFamily: _kFontFam);
  static const IconData insect = const IconData(0xe83b, fontFamily: _kFontFam);
  static const IconData login = const IconData(0xe83c, fontFamily: _kFontFam);
  static const IconData mite = const IconData(0xe83d, fontFamily: _kFontFam);
  static const IconData plant = const IconData(0xe83e, fontFamily: _kFontFam);
  static const IconData plantshand = const IconData(0xe83f, fontFamily: _kFontFam);
  static const IconData virus = const IconData(0xe840, fontFamily: _kFontFam);
  static const IconData writepost = const IconData(0xe841, fontFamily: _kFontFam);
  static const IconData arrows_cw = const IconData(0xe842, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xe843, fontFamily: _kFontFam);
  static const IconData gift = const IconData(0xe844, fontFamily: _kFontFam);
  static const IconData leaf = const IconData(0xe849, fontFamily: _kFontFam);
  static const IconData smile = const IconData(0xe854, fontFamily: _kFontFam);
  static const IconData sad = const IconData(0xe855, fontFamily: _kFontFam);
  static const IconData neutral = const IconData(0xe856, fontFamily: _kFontFam);
  static const IconData alarm = const IconData(0xe858, fontFamily: _kFontFam);
  static const IconData hourglass = const IconData(0xe85f, fontFamily: _kFontFam);
  static const IconData bug = const IconData(0xe869, fontFamily: _kFontFam);
  static const IconData thumbs_up = const IconData(0xe86d, fontFamily: _kFontFam);
  static const IconData thumbs_down = const IconData(0xe86e, fontFamily: _kFontFam);
  static const IconData question_circle = const IconData(0xe87d, fontFamily: _kFontFam);
  static const IconData frame_expand = const IconData(0xe88c, fontFamily: _kFontFam);
  static const IconData text_size = const IconData(0xe892, fontFamily: _kFontFam);
  static const IconData sort_amount_asc = const IconData(0xe8a4, fontFamily: _kFontFam);
  static const IconData hand = const IconData(0xe8a5, fontFamily: _kFontFam);
  static const IconData stethoscope = const IconData(0xf0f1, fontFamily: _kFontFam);
  static const IconData h_sigh = const IconData(0xf0fd, fontFamily: _kFontFam);
  static const IconData facebook_rect = const IconData(0xf301, fontFamily: _kFontFam);
  static const IconData twitter_bird = const IconData(0xf303, fontFamily: _kFontFam);
  static const IconData icq = const IconData(0xf304, fontFamily: _kFontFam);
  static const IconData github = const IconData(0xf308, fontFamily: _kFontFam);
  static const IconData googleplus_rect = const IconData(0xf309, fontFamily: _kFontFam);
  static const IconData skype = const IconData(0xf30b, fontFamily: _kFontFam);
  static const IconData linkedin_rect = const IconData(0xf31b, fontFamily: _kFontFam);
  static const IconData picasa = const IconData(0xf31c, fontFamily: _kFontFam);
  static const IconData instagram_filled = const IconData(0xf31f, fontFamily: _kFontFam);
}
